GHA: Push config after optimization

diff --git a/.github/workflows/optimize-indi-rsi-period.yml b/.github/workflows/optimize-indi-rsi-period.yml
--- a/.github/workflows/optimize-indi-rsi-period.yml
+++ b/.github/workflows/optimize-indi-rsi-period.yml
@@ -52,6 +52,9 @@ jobs:
           name: sets
           path: 'sets/optimize/*.set'
   Optimize:
+    defaults:
+      run:
+        shell: bash --noprofile --norc -eo pipefail -x {0}
     needs: Compile
     runs-on: ubuntu-latest
     strategy:
@@ -70,6 +73,7 @@ jobs:
       - uses: ea31337/mql-tester-action@master
         with:
           BtDest: ${{ github.workspace }}/_results
+          BtDays: 1-10
           BtMonths: 1
           BtPair: ${{ matrix.pair }}
           BtYears: 2019
@@ -100,7 +104,6 @@ jobs:
       - uses: actions/checkout@v2
       - name: Update config file
         run: |
-          set | grep ^RSI
           ex -u NONE -V1 \
             +"%s@\\<period[^=]\\?=\\s\\?[^-.0-9]\\+\\zs[^;$]\\+@${!pname}@" \
             -scwq! ./config/${{ matrix.pair }}_${{ matrix.tf }}.h
@@ -109,3 +112,58 @@ jobs:
         with:
           name: config
           path: ./config/${{ matrix.pair }}_${{ matrix.tf }}.h
+  Push:
+    needs: Optimize
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          persist-credentials: false
+          # Otherwise, you will failed to push refs to dest repo.
+          fetch-depth: 0
+      - uses: actions/download-artifact@v2
+        with:
+          name: config
+          path: config
+      - uses: actions/download-artifact@v2
+        with:
+          name: results
+          path: .results
+      - name: Parse results
+        run: |
+          echo RES_DD=$(jq -r '."Drawdown %"' .results/*.json) >> $GITHUB_ENV
+          echo RES_PF=$(jq -r '."Profit factor"' .results/*.json) >> $GITHUB_ENV
+          echo RES_TT=$(jq -r '."Total trades"' .results/*.json) >> $GITHUB_ENV
+        shell: bash -ex {0}
+      - name: Commit files
+        env:
+          GIT_EMAIL: ${{ github.actor }}@users.noreply.github.com
+          GIT_NAME: ${{ github.actor }}
+        run: |
+          echo .results >> .git/info/exclude
+          git config --local core.autocrlf false
+          git config --local user.email $GIT_EMAIL
+          git config --local user.name $GIT_NAME
+          git add . && git add --renormalize .
+          git pull origin ${{ github.ref }} --autostash --rebase -X ours
+          git commit --allow-empty -am "${{ github.workflow }}"
+          NO_PAGER=1 git --no-pager diff HEAD^
+      - name: Push changes
+        env:
+          DD: ${{ env.RES_DD }}
+          PF: ${{ env.RES_PF }}
+          TT: ${{ env.RES_TT }}
+        uses: ad-m/github-push-action@master
+        with:
+          branch: dev-optimize-${{ env.PF }}pf-${{ env.DD }}dd-${{ env.TT }}tt
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Re-pull on failure
+        if: ${{ failure() }}
+        run: git pull origin ${{ github.ref }} --autostash --rebase -X ours
+      - name: Re-push on failure
+        if: ${{ failure() }}
+        uses: ad-m/github-push-action@master
+        with:
+          branch: ${{ github.ref }}
+          force: true
+          github_token: ${{ secrets.GITHUB_TOKEN }}
